# Generated by Django 3.0.7 on 2020-07-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbb',
            fields=[
                ('n', models.CharField(max_length=25)),
                ('em', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('p', models.CharField(max_length=15)),
                ('food', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=20)),
                ('sportsman', models.CharField(max_length=15)),
                ('actor', models.CharField(max_length=15)),
                ('game', models.CharField(max_length=15)),
                ('song', models.CharField(max_length=15)),
                ('movie', models.CharField(max_length=15)),
                ('sports', models.CharField(max_length=15)),
                ('enter', models.CharField(max_length=15)),
                ('person', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=2000)),
            ],
        ),
    ]
